/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hello */

#ifndef _Included_hello
#define _Included_hello
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hello
 * Method:    print_hello_world
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_hello_print_1hello_1world
  (JNIEnv *, jobject);

/*
 * Class:     hello
 * Method:    yk_get_max
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_hello_yk_1get_1max
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     hello
 * Method:    yk_add_prefix
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_hello_yk_1add_1prefix
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
